# version: '3.9'

# services:
#   portfolio:
#     build: .
#     container_name: aarati_portfolio
#     ports:
#       - "8080:8080"
#     security_opt:
#       - no-new-privileges:true
#     read_only: true
#     tmpfs:
#       - /tmp
#       - /var/cache/nginx
#       - /var/run
#     restart: unless-stopped
version: '3.9'

services:
  portfolio:
    build: .
    container_name: aarati_portfolio
    ports:
      - "8080:80"
    
    # D01: Runtime enforcement
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    
    # Resource limits
    mem_limit: 256m
    cpus: 0.5
    restart: unless-stopped